// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Cae_PictureTouch","status":true,"description":"v1.6 - Run events or scripts when pictures are touched/hovered.","parameters":{"Minimum Opacity":"1","Minimum Opacity For All":"false","Unbind on Show":"false","Unbind on Erase":"true","Disable on Trigger":"false","Add Save Data":"true","Always Update Hover":"false","Picture ID Variable":"0"}},
{"name":"GALV_ChoicePauseMZ","status":true,"description":"(v.1.0) Prevent the player from accidentally selecting a choice by adding a pause","parameters":{"Pause Time":"20"}},
{"name":"GALV_VisualNovelChoicesMZ","status":true,"description":"(v.1.0) Changes how the \"Choice\" message boxes display to appear more like visual novels.","parameters":{"Command Width":"350","Command Height":"70","Always Middle":"true","Message Gap":"45","Disabled Button":"3"}},
{"name":"MOG_PictureEffects","status":true,"description":"(v1.1) O plugin permite animar as imagens.","parameters":{}},
{"name":"EliMZ_PauseGame","status":false,"description":"♦3.1.0♦ Adds a Pause Scene like retro games!","parameters":{"commonEvent":"0","switch":"0","separator1":"","overwrite":"true","keyboardButton":"none","gamepadButton":"none","separator2":"","enableScreenButton":"true","buttonImage":"","position":"{\"alignX\":\"center\",\"offsetX\":\"0\",\"alignY\":\"center\",\"offsetY\":\"0\"}","separator3":"","pauseSe":"","pauseSeConfig":"0, 100, 60","separator4":"","stopGameTime":"true","pauseImage":"","pauseAnime":"","sceneMapBackground":"false","blur":"false","backgroundOpacity":"192"}}
];
