// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"pulartelainicial","status":true,"description":"Pula a tela de título padrão e inicia o jogo direto em um mapa definido.","parameters":{"startMapId":"3","startX":"1","startY":"1"}},
{"name":"Cae_PictureTouch","status":true,"description":"v1.6 - Run events or scripts when pictures are touched/hovered.","parameters":{"Minimum Opacity":"1","Minimum Opacity For All":"false","Unbind on Show":"false","Unbind on Erase":"true","Disable on Trigger":"false","Add Save Data":"true","Always Update Hover":"false","Picture ID Variable":"0"}},
{"name":"GALV_ChoicePauseMZ","status":true,"description":"(v.1.0) Prevent the player from accidentally selecting a choice by adding a pause","parameters":{"Pause Time":"20"}},
{"name":"GALV_VisualNovelChoicesMZ","status":true,"description":"(v.1.0) Changes how the \"Choice\" message boxes display to appear more like visual novels.","parameters":{"Command Width":"350","Command Height":"70","Always Middle":"true","Message Gap":"50","Disabled Button":"3"}},
{"name":"MOG_PictureEffects","status":true,"description":"(v1.1) O plugin permite animar as imagens.","parameters":{}},
{"name":"Cae_ChoiceShuffle","status":true,"description":"v1.0 - Randomly reorder Show Choices when shuffle mode is on.","parameters":{"Default Shuffle":"true","Add Save Data":"false","--- Advanced ---":"","Save Property Name":"ChoiceShuffle"}},
{"name":"menupause","status":true,"description":"Adiciona um menu de pausa customizável.","parameters":{"menuBackground":"pause_bg","buttonBackground":"btn_bg","fontSize":"26","fontFace":"rmmz-mainfont","buttonSpacing":"70","pauseTitle":"  ","titleFontSize":"48","titleOffsetY":"-260","titleMapId":"3","titleMapX":"1","titleMapY":"1"}},
{"name":"saveload","status":true,"description":"Sistema Save/Load VN Visual Custom","parameters":{"saveBackground":"save_bg","slotImage":"save_slot","slotHoverImage":"save_slot_hover","closeButtonImage":"save_close","nextButtonImage":"save_next","prevButtonImage":"save_prev","fontFace":"rmmz-mainfont","fontSize":"18","dayVariableId":"12"}}
];
